image:
  repository: vaishnavyejju/portfolio
  tag: 65407f2633321ce0f200271145117d3194be9188
  pullpolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: false
serviceaccount:
  enabled: false
autoscaling:
  enabled: false